// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hierarchy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Remotedebugger {

  /// <summary>Holder for reflection information generated from hierarchy.proto</summary>
  public static partial class HierarchyReflection {

    #region Descriptor
    /// <summary>File descriptor for hierarchy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HierarchyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9oaWVyYXJjaHkucHJvdG8SDnJlbW90ZWRlYnVnZ2VyGh9nb29nbGUvcHJv",
            "dG9idWYvdGltZXN0YW1wLnByb3RvIvEECglIaWVyYXJjaHkSLQoJdGltZXN0",
            "YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI2CgtnYW1l",
            "T2JqZWN0cxgCIAMoCzIhLnJlbW90ZWRlYnVnZ2VyLkhpZXJhcmNoeS5HYW1l",
            "T2JqGvwDCgdHYW1lT2JqEg0KBWluZGV4GAEgASgFEgwKBG5hbWUYAiABKAkS",
            "PAoJdHJhbnNmb3JtGAMgASgLMikucmVtb3RlZGVidWdnZXIuSGllcmFyY2h5",
            "LkdhbWVPYmouVHJhbnNmbxI7Cgpjb21wb25lbnRzGAQgAygLMicucmVtb3Rl",
            "ZGVidWdnZXIuSGllcmFyY2h5LkdhbWVPYmouQ29tcG8SMwoIY2hpbGRyZW4Y",
            "BSADKAsyIS5yZW1vdGVkZWJ1Z2dlci5IaWVyYXJjaHkuR2FtZU9iahokCgVD",
            "b21wbxINCgVpbmRleBgBIAEoBRIMCgRuYW1lGAIgASgJGv0BCgdUcmFuc2Zv",
            "EkIKCHBvc2l0aW9uGAEgASgLMjAucmVtb3RlZGVidWdnZXIuSGllcmFyY2h5",
            "LkdhbWVPYmouVHJhbnNmby5WZWN0b3ISQgoIcm90YXRpb24YAiABKAsyMC5y",
            "ZW1vdGVkZWJ1Z2dlci5IaWVyYXJjaHkuR2FtZU9iai5UcmFuc2ZvLlZlY3Rv",
            "chI/CgVzY2FsZRgDIAEoCzIwLnJlbW90ZWRlYnVnZ2VyLkhpZXJhcmNoeS5H",
            "YW1lT2JqLlRyYW5zZm8uVmVjdG9yGikKBlZlY3RvchIJCgF4GAEgASgCEgkK",
            "AXkYAiABKAISCQoBehgDIAEoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Remotedebugger.Hierarchy), global::Remotedebugger.Hierarchy.Parser, new[]{ "Timestamp", "GameObjects" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Remotedebugger.Hierarchy.Types.GameObj), global::Remotedebugger.Hierarchy.Types.GameObj.Parser, new[]{ "Index", "Name", "Transform", "Components", "Children" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo), global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo.Parser, new[]{ "Index", "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo), global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Parser, new[]{ "Position", "Rotation", "Scale" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector), global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null)})})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Hierarchy : pb::IMessage<Hierarchy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Hierarchy> _parser = new pb::MessageParser<Hierarchy>(() => new Hierarchy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Hierarchy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Remotedebugger.HierarchyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Hierarchy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Hierarchy(Hierarchy other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      gameObjects_ = other.gameObjects_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Hierarchy Clone() {
      return new Hierarchy(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "gameObjects" field.</summary>
    public const int GameObjectsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Remotedebugger.Hierarchy.Types.GameObj> _repeated_gameObjects_codec
        = pb::FieldCodec.ForMessage(18, global::Remotedebugger.Hierarchy.Types.GameObj.Parser);
    private readonly pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj> gameObjects_ = new pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj> GameObjects {
      get { return gameObjects_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Hierarchy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Hierarchy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if(!gameObjects_.Equals(other.gameObjects_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= gameObjects_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      gameObjects_.WriteTo(output, _repeated_gameObjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      gameObjects_.WriteTo(ref output, _repeated_gameObjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      size += gameObjects_.CalculateSize(_repeated_gameObjects_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Hierarchy other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      gameObjects_.Add(other.gameObjects_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            gameObjects_.AddEntriesFrom(input, _repeated_gameObjects_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            gameObjects_.AddEntriesFrom(ref input, _repeated_gameObjects_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Hierarchy message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class GameObj : pb::IMessage<GameObj>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<GameObj> _parser = new pb::MessageParser<GameObj>(() => new GameObj());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GameObj> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Remotedebugger.Hierarchy.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameObj() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameObj(GameObj other) : this() {
          index_ = other.index_;
          name_ = other.name_;
          transform_ = other.transform_ != null ? other.transform_.Clone() : null;
          components_ = other.components_.Clone();
          children_ = other.children_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameObj Clone() {
          return new GameObj(this);
        }

        /// <summary>Field number for the "index" field.</summary>
        public const int IndexFieldNumber = 1;
        private int index_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Index {
          get { return index_; }
          set {
            index_ = value;
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 2;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "transform" field.</summary>
        public const int TransformFieldNumber = 3;
        private global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo transform_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo Transform {
          get { return transform_; }
          set {
            transform_ = value;
          }
        }

        /// <summary>Field number for the "components" field.</summary>
        public const int ComponentsFieldNumber = 4;
        private static readonly pb::FieldCodec<global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo> _repeated_components_codec
            = pb::FieldCodec.ForMessage(34, global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo.Parser);
        private readonly pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo> components_ = new pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj.Types.Compo> Components {
          get { return components_; }
        }

        /// <summary>Field number for the "children" field.</summary>
        public const int ChildrenFieldNumber = 5;
        private static readonly pb::FieldCodec<global::Remotedebugger.Hierarchy.Types.GameObj> _repeated_children_codec
            = pb::FieldCodec.ForMessage(42, global::Remotedebugger.Hierarchy.Types.GameObj.Parser);
        private readonly pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj> children_ = new pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Remotedebugger.Hierarchy.Types.GameObj> Children {
          get { return children_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as GameObj);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GameObj other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Index != other.Index) return false;
          if (Name != other.Name) return false;
          if (!object.Equals(Transform, other.Transform)) return false;
          if(!components_.Equals(other.components_)) return false;
          if(!children_.Equals(other.children_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Index != 0) hash ^= Index.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (transform_ != null) hash ^= Transform.GetHashCode();
          hash ^= components_.GetHashCode();
          hash ^= children_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Index != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Index);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (transform_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Transform);
          }
          components_.WriteTo(output, _repeated_components_codec);
          children_.WriteTo(output, _repeated_children_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Index != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Index);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (transform_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Transform);
          }
          components_.WriteTo(ref output, _repeated_components_codec);
          children_.WriteTo(ref output, _repeated_children_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Index != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (transform_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
          }
          size += components_.CalculateSize(_repeated_components_codec);
          size += children_.CalculateSize(_repeated_children_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GameObj other) {
          if (other == null) {
            return;
          }
          if (other.Index != 0) {
            Index = other.Index;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.transform_ != null) {
            if (transform_ == null) {
              Transform = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo();
            }
            Transform.MergeFrom(other.Transform);
          }
          components_.Add(other.components_);
          children_.Add(other.children_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Index = input.ReadInt32();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
              case 26: {
                if (transform_ == null) {
                  Transform = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo();
                }
                input.ReadMessage(Transform);
                break;
              }
              case 34: {
                components_.AddEntriesFrom(input, _repeated_components_codec);
                break;
              }
              case 42: {
                children_.AddEntriesFrom(input, _repeated_children_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Index = input.ReadInt32();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
              case 26: {
                if (transform_ == null) {
                  Transform = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo();
                }
                input.ReadMessage(Transform);
                break;
              }
              case 34: {
                components_.AddEntriesFrom(ref input, _repeated_components_codec);
                break;
              }
              case 42: {
                children_.AddEntriesFrom(ref input, _repeated_children_codec);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the GameObj message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public sealed partial class Compo : pb::IMessage<Compo>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Compo> _parser = new pb::MessageParser<Compo>(() => new Compo());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Compo> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Remotedebugger.Hierarchy.Types.GameObj.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Compo() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Compo(Compo other) : this() {
              index_ = other.index_;
              name_ = other.name_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Compo Clone() {
              return new Compo(this);
            }

            /// <summary>Field number for the "index" field.</summary>
            public const int IndexFieldNumber = 1;
            private int index_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int Index {
              get { return index_; }
              set {
                index_ = value;
              }
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 2;
            private string name_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Name {
              get { return name_; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Compo);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Compo other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Index != other.Index) return false;
              if (Name != other.Name) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Index != 0) hash ^= Index.GetHashCode();
              if (Name.Length != 0) hash ^= Name.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Index != 0) {
                output.WriteRawTag(8);
                output.WriteInt32(Index);
              }
              if (Name.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Index != 0) {
                output.WriteRawTag(8);
                output.WriteInt32(Index);
              }
              if (Name.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Name);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Index != 0) {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
              }
              if (Name.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Compo other) {
              if (other == null) {
                return;
              }
              if (other.Index != 0) {
                Index = other.Index;
              }
              if (other.Name.Length != 0) {
                Name = other.Name;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    Index = input.ReadInt32();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    Index = input.ReadInt32();
                    break;
                  }
                  case 18: {
                    Name = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

          public sealed partial class Transfo : pb::IMessage<Transfo>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Transfo> _parser = new pb::MessageParser<Transfo>(() => new Transfo());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Transfo> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Remotedebugger.Hierarchy.Types.GameObj.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Transfo() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Transfo(Transfo other) : this() {
              position_ = other.position_ != null ? other.position_.Clone() : null;
              rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
              scale_ = other.scale_ != null ? other.scale_.Clone() : null;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Transfo Clone() {
              return new Transfo(this);
            }

            /// <summary>Field number for the "position" field.</summary>
            public const int PositionFieldNumber = 1;
            private global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector position_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector Position {
              get { return position_; }
              set {
                position_ = value;
              }
            }

            /// <summary>Field number for the "rotation" field.</summary>
            public const int RotationFieldNumber = 2;
            private global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector rotation_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector Rotation {
              get { return rotation_; }
              set {
                rotation_ = value;
              }
            }

            /// <summary>Field number for the "scale" field.</summary>
            public const int ScaleFieldNumber = 3;
            private global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector scale_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector Scale {
              get { return scale_; }
              set {
                scale_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Transfo);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Transfo other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!object.Equals(Position, other.Position)) return false;
              if (!object.Equals(Rotation, other.Rotation)) return false;
              if (!object.Equals(Scale, other.Scale)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (position_ != null) hash ^= Position.GetHashCode();
              if (rotation_ != null) hash ^= Rotation.GetHashCode();
              if (scale_ != null) hash ^= Scale.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (position_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(Position);
              }
              if (rotation_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Rotation);
              }
              if (scale_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(Scale);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (position_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(Position);
              }
              if (rotation_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Rotation);
              }
              if (scale_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(Scale);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (position_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
              }
              if (rotation_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
              }
              if (scale_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scale);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Transfo other) {
              if (other == null) {
                return;
              }
              if (other.position_ != null) {
                if (position_ == null) {
                  Position = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                }
                Position.MergeFrom(other.Position);
              }
              if (other.rotation_ != null) {
                if (rotation_ == null) {
                  Rotation = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                }
                Rotation.MergeFrom(other.Rotation);
              }
              if (other.scale_ != null) {
                if (scale_ == null) {
                  Scale = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                }
                Scale.MergeFrom(other.Scale);
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    if (position_ == null) {
                      Position = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Position);
                    break;
                  }
                  case 18: {
                    if (rotation_ == null) {
                      Rotation = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Rotation);
                    break;
                  }
                  case 26: {
                    if (scale_ == null) {
                      Scale = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Scale);
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    if (position_ == null) {
                      Position = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Position);
                    break;
                  }
                  case 18: {
                    if (rotation_ == null) {
                      Rotation = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Rotation);
                    break;
                  }
                  case 26: {
                    if (scale_ == null) {
                      Scale = new global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Types.Vector();
                    }
                    input.ReadMessage(Scale);
                    break;
                  }
                }
              }
            }
            #endif

            #region Nested types
            /// <summary>Container for nested types declared in the Transfo message type.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static partial class Types {
              public sealed partial class Vector : pb::IMessage<Vector>
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  , pb::IBufferMessage
              #endif
              {
                private static readonly pb::MessageParser<Vector> _parser = new pb::MessageParser<Vector>(() => new Vector());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pb::MessageParser<Vector> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Remotedebugger.Hierarchy.Types.GameObj.Types.Transfo.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Vector() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Vector(Vector other) : this() {
                  x_ = other.x_;
                  y_ = other.y_;
                  z_ = other.z_;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Vector Clone() {
                  return new Vector(this);
                }

                /// <summary>Field number for the "x" field.</summary>
                public const int XFieldNumber = 1;
                private float x_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public float X {
                  get { return x_; }
                  set {
                    x_ = value;
                  }
                }

                /// <summary>Field number for the "y" field.</summary>
                public const int YFieldNumber = 2;
                private float y_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public float Y {
                  get { return y_; }
                  set {
                    y_ = value;
                  }
                }

                /// <summary>Field number for the "z" field.</summary>
                public const int ZFieldNumber = 3;
                private float z_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public float Z {
                  get { return z_; }
                  set {
                    z_ = value;
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override bool Equals(object other) {
                  return Equals(other as Vector);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public bool Equals(Vector other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
                  if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
                  if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override int GetHashCode() {
                  int hash = 1;
                  if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
                  if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
                  if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void WriteTo(pb::CodedOutputStream output) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  output.WriteRawMessage(this);
                #else
                  if (X != 0F) {
                    output.WriteRawTag(13);
                    output.WriteFloat(X);
                  }
                  if (Y != 0F) {
                    output.WriteRawTag(21);
                    output.WriteFloat(Y);
                  }
                  if (Z != 0F) {
                    output.WriteRawTag(29);
                    output.WriteFloat(Z);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                  if (X != 0F) {
                    output.WriteRawTag(13);
                    output.WriteFloat(X);
                  }
                  if (Y != 0F) {
                    output.WriteRawTag(21);
                    output.WriteFloat(Y);
                  }
                  if (Z != 0F) {
                    output.WriteRawTag(29);
                    output.WriteFloat(Z);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(ref output);
                  }
                }
                #endif

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int CalculateSize() {
                  int size = 0;
                  if (X != 0F) {
                    size += 1 + 4;
                  }
                  if (Y != 0F) {
                    size += 1 + 4;
                  }
                  if (Z != 0F) {
                    size += 1 + 4;
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(Vector other) {
                  if (other == null) {
                    return;
                  }
                  if (other.X != 0F) {
                    X = other.X;
                  }
                  if (other.Y != 0F) {
                    Y = other.Y;
                  }
                  if (other.Z != 0F) {
                    Z = other.Z;
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(pb::CodedInputStream input) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  input.ReadRawMessage(this);
                #else
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 13: {
                        X = input.ReadFloat();
                        break;
                      }
                      case 21: {
                        Y = input.ReadFloat();
                        break;
                      }
                      case 29: {
                        Z = input.ReadFloat();
                        break;
                      }
                    }
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                      case 13: {
                        X = input.ReadFloat();
                        break;
                      }
                      case 21: {
                        Y = input.ReadFloat();
                        break;
                      }
                      case 29: {
                        Z = input.ReadFloat();
                        break;
                      }
                    }
                  }
                }
                #endif

              }

            }
            #endregion

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
